#line 2 "interface/lex.yy.c"

#line 4 "interface/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[195] =
    {   0,
        0,    0,   62,   61,   60,   45,   39,   39,   39,   61,
       37,   36,   38,   35,   32,   34,   41,   43,   42,   33,
       44,   44,   44,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   61,   39,   60,   39,
       39,   44,   39,    0,   40,   41,   42,   41,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   10,   14,   39,   39,   39,   39,   39,   39,   30,
       48,   55,   29,   51,   53,   57,   39,   13,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       15,   20,   39,   39,   39,   39,   39,   39,   39,   49,

       50,    0,   49,   56,   55,   56,    0,   52,   52,   54,
       54,   58,   59,    0,   57,   39,   17,   39,   39,   39,
       39,   39,   39,   23,    5,   39,   39,   39,   39,    2,
       39,   39,   39,   39,   39,   39,   39,   56,   27,   26,
       31,   39,   39,   39,   39,   39,   39,   11,   39,   39,
       39,   39,   39,    9,   39,   39,    6,   46,   28,   28,
       39,    8,   39,    7,   18,   39,    1,   39,   39,   39,
        4,    3,   39,   47,   47,   39,   39,   39,   12,   19,
       39,   16,   39,   22,   39,   39,   39,   25,   39,   39,
       21,   39,   24,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    6,    7,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,   22,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,    6,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,   45,    6,
        1,   46,    1,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,    6,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,    6,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    1,    1,    1,    6,    6,    6,    6,
        1,    6,    6,    6,    1,    1,    1,    6,    6,    6,
        6,    1,    1,    1,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    3,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    4,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static const flex_int16_t yy_base[204] =
    {   0,
        0,    0,  287,  951,   71,  951,   57,   59,   61,  275,
      951,  951,  951,   65,  951,   68,  250,  951,   69,  951,
      246,  951,  240,   71,  116,  165,   70,   77,   75,   79,
       83,  136,  138,   81,   93,  149,  148,  142,  118,  154,
      160,  951,  176,  248,  246,  222,  109,  216,  199,  200,
      209,  211,  215,  221,  217,  223,  238,  253,  258,  264,
      260,  262,  276,  294,  300,  302,  309,  320,  319,  951,
      147,   37,  154,  147,  130,  218,  321,  327,  335,  343,
      354,  361,  370,  369,  381,  386,  391,  387,  410,  416,
      425,  396,  433,  448,  457,  459,  463,  437,  474,  157,

      951,  164,  241,    0,  135,  126,  110,    0,  114,    0,
       93,  206,  951,  249,  295,  469,  478,  482,  486,  496,
      518,  508,  526,  532,  533,  538,  540,  544,  550,  552,
      570,  556,  582,  586,  595,  597,  608,   81,   79,  603,
      609,  621,  620,  642,  647,  655,  629,  638,  659,  667,
      663,  685,  676,  689,  693,  702,  697,   77,    0,   73,
      710,  701,  722,  727,  735,  736,  737,  748,  747,  756,
      749,  754,  760,    0,   68,  762,  773,  789,  794,  795,
      803,  812,  816,  814,  818,  828,  827,  829,  848,  850,
      852,  854,  862,  951,  112,  920,  924,  927,  931,  935,

      939,  942,  946
    } ;

static const flex_int16_t yy_def[204] =
    {   0,
      194,    1,  194,  194,  194,  194,  195,  195,  195,  196,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  194,  195,  194,  195,
      195,  194,  195,  196,  194,  194,  194,  194,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  194,
      197,  198,  194,  199,  200,  201,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  197,

      194,  194,  197,  198,  198,  198,  194,  199,  199,  200,
      200,  201,  194,  194,  201,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  198,  202,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  203,  202,  202,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  203,  203,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,    0,  194,  194,  194,  194,  194,  194,

      194,  194,  194
    } ;

static const flex_int16_t yy_nxt[1024] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,    4,   24,    8,   25,   26,    8,   27,    8,    8,
       28,   29,    8,    8,    8,   30,   31,   32,   33,   34,
        8,   35,   36,    8,    8,   37,    4,    8,   24,    8,
       25,   26,    8,   27,    8,   38,   28,   29,    8,    8,
        8,   30,   31,    8,   32,   33,   34,    8,   35,   36,
        8,    8,   39,   41,   39,   41,   42,   41,  194,   46,
      194,   47,   46,   46,   47,   47,   41,   41,  105,  194,
      194,   41,  106,   41,  194,   41,  194,   41,  194,   41,

      194,   61,  194,   67,   43,   49,   43,   58,   43,   41,
       59,   60,  194,   62,   40,   68,   63,   43,   43,   39,
       64,   39,   43,   46,   43,   47,   43,   61,   43,   67,
       43,   49,   41,  175,   58,  194,   59,   60,  160,   62,
       43,   68,  175,   63,  160,   50,  158,   64,   51,  101,
      102,   52,   41,   53,   41,  194,  111,  194,   41,  194,
      194,  194,   65,   43,   66,   41,  101,  102,  194,   70,
       41,   50,  109,  194,   51,  139,   41,   52,   69,  194,
       53,   41,  138,   43,  194,   43,  105,   54,   65,   43,
       66,   55,   41,  111,   77,  194,   43,  103,   71,   72,

       56,   43,   57,   73,   69,  109,   74,   43,  194,  194,
      107,   75,   43,   54,   76,   41,   41,   55,  194,  194,
      113,  114,   79,   43,   78,   41,   56,   41,  194,   57,
      194,   41,   48,   41,  194,   80,  194,   41,   48,   41,
      194,   82,  194,  101,  102,   81,   43,   43,   79,   84,
       78,  113,  114,   44,   41,   45,   43,  194,   43,   42,
       83,   80,   43,   85,   43,   42,   48,   82,   43,   41,
       43,   81,  194,   86,   41,   84,   41,  194,   41,  194,
       41,  194,   45,  194,  115,   43,  194,   83,   87,   89,
       85,  103,   41,  194,   88,  194,  194,  113,  114,   86,

       43,  194,   90,   91,   92,   43,  194,   43,  194,   43,
       41,   43,  194,  194,   87,   89,   41,  194,   41,  194,
       88,  194,  194,   43,   93,   41,  194,   94,  194,   90,
       91,   92,   96,  194,   95,   41,   41,   41,  194,  194,
      194,   43,  194,   41,  194,   99,  194,   43,  194,   43,
       93,   41,   97,   94,  194,  194,   43,   98,   96,   41,
       95,  115,  194,  194,  194,  118,   43,   43,   43,  194,
       41,   99,  117,  194,   43,  194,  194,   41,   97,  116,
      194,  194,   43,  120,   98,   41,   41,  194,  194,  194,
       43,  118,  121,  119,  194,  122,  194,   41,  194,  117,

      194,   43,   41,   41,  123,  194,  194,   41,   43,  120,
      194,  194,   41,  194,  194,  194,   43,   43,  121,  126,
      119,  122,  124,  194,  125,  194,   41,  194,   43,  194,
      123,  194,   41,   43,   43,  194,  127,  194,   43,  194,
      194,   41,  128,   43,  194,  126,  194,  194,  124,   41,
      125,  129,  194,   41,  194,  194,  194,   43,  194,  194,
      130,  136,  127,   43,   41,  194,  131,  194,  128,  194,
      194,  194,   43,   41,  132,   41,  194,  129,  194,   41,
       43,  194,  194,  133,   43,   41,  130,  136,  194,  194,
       41,  134,  131,  194,   41,   43,  194,  194,   41,  194,

      132,  194,   41,  135,   43,  194,   43,  194,  194,  133,
       43,  137,   41,  194,  194,  194,   43,  134,  194,  141,
      194,   43,  194,  142,   41,   43,  194,  194,  194,   43,
      135,  140,  194,   43,   41,  143,  194,  194,  137,  194,
      194,  144,   41,   43,  194,  194,  141,  145,   41,   41,
      142,  194,  194,  194,   41,   43,   41,  194,  146,  194,
       41,  194,  143,  194,  147,   43,   41,  144,   41,  194,
      194,  194,   41,   43,  145,  194,  194,  194,  150,   43,
       43,  149,  194,  148,  146,   43,   41,   43,  194,  194,
      147,   43,  151,  152,  194,  194,  194,   43,   41,   43,

      194,  194,   41,   43,  150,  194,  153,  194,  149,  194,
      148,   41,  154,   41,  194,  194,  194,   43,  151,   41,
      152,  155,  194,  194,   41,   41,  156,  194,  194,   43,
      194,  194,  153,   43,  157,  194,   41,   41,  154,  194,
      194,  194,   43,  194,   43,   41,  162,  155,  194,  194,
       43,  161,  156,  194,   41,   43,   43,  194,   41,  194,
      157,  194,  166,   41,  163,  194,  194,   43,   43,  194,
      194,   41,  162,  164,  194,   41,   43,  161,  194,   41,
      194,  165,  194,   41,  194,   43,  194,  194,  166,   43,
      163,  194,   41,  168,   43,  194,  194,  194,  167,  164,

      169,   41,   43,  194,  194,   41,   43,  165,  194,   41,
       43,  170,  194,   41,   43,  171,  194,   41,   41,  168,
      194,  194,  194,   43,  173,  167,   41,  169,  194,  194,
      194,  172,   43,  176,  194,  194,   43,  170,   41,  194,
       43,  194,  171,   41,   43,  194,  194,  194,   43,   43,
      173,   41,   41,   41,  194,  194,  194,   43,  172,  176,
      177,  194,  178,   41,   41,   41,  194,  194,  194,   43,
       41,  194,   41,  194,   43,  194,   41,  194,   41,  194,
      194,  194,   43,   43,   43,  179,  194,  177,  178,   41,
      181,  180,  194,  194,   43,   43,   43,  182,  194,  184,

      194,   43,  183,   43,  194,   41,  194,   43,  194,   43,
       41,   41,  179,  194,  194,  194,  181,  194,  180,   41,
       43,  194,  194,  185,  182,  184,  194,  186,   41,  183,
       41,  194,   41,  194,   41,  194,   43,  194,  194,  194,
      194,   43,   43,   41,   41,   41,  194,  194,  194,  185,
       43,  194,  194,  186,  189,  187,  194,  188,  194,   43,
      194,   43,  190,   43,   41,   43,   41,  194,   41,  194,
       41,  194,  194,  194,   43,   43,   43,  194,   41,  194,
      189,  194,  187,  194,  188,  194,  191,  192,  190,  194,
      194,  194,  193,  194,  194,   43,  194,   43,  194,   43,

      194,   43,  194,  194,  194,  194,  194,  194,  194,   43,
      194,  194,  194,  191,  192,  194,  194,  194,  194,  193,
       44,   44,   44,   44,  100,  100,  100,  104,  194,  104,
      104,  108,  194,  108,  108,  110,  194,  110,  110,  112,
      112,  112,  159,  194,  159,  159,  174,  194,  174,  174,
        3,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194
    } ;

static const flex_int16_t yy_chk[1024] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    7,    5,    8,    7,    9,    8,   14,
        9,   14,   16,   19,   16,   19,   27,   24,   72,   27,
       24,   29,   72,   28,   29,   30,   28,   34,   30,   31,

       34,   29,   31,   34,    7,   24,    8,   27,    9,   35,
       28,   28,   35,   30,  195,   35,   30,   27,   24,   39,
       31,   39,   29,   47,   28,   47,   30,   29,   34,   34,
       31,   24,   25,  175,   27,   25,   28,   28,  160,   30,
       35,   35,  158,   30,  139,   25,  138,   31,   25,   71,
       71,   25,   32,   25,   33,   32,  111,   33,   38,  100,
      100,   38,   32,   25,   33,   36,  102,  102,   36,   37,
       40,   25,  109,   40,   25,  107,   41,   25,   36,   41,
       25,   26,  106,   32,   26,   33,  105,   26,   32,   38,
       33,   26,   43,   75,   38,   43,   36,   71,   37,   37,

       26,   40,   26,   37,   36,   74,   37,   41,  112,  112,
       73,   37,   26,   26,   37,   49,   50,   26,   49,   50,
       76,   76,   50,   43,   49,   51,   26,   52,   51,   26,
       52,   53,   48,   55,   53,   51,   55,   54,   46,   56,
       54,   53,   56,  103,  103,   52,   49,   50,   50,   55,
       49,  114,  114,   45,   57,   44,   51,   57,   52,   23,
       54,   51,   53,   56,   55,   21,   17,   53,   54,   58,
       56,   52,   58,   57,   59,   55,   61,   59,   62,   61,
       60,   62,   10,   60,   76,   57,    3,   54,   58,   60,
       56,  103,   63,    0,   59,   63,    0,  115,  115,   57,

       58,    0,   60,   60,   61,   59,    0,   61,    0,   62,
       64,   60,    0,   64,   58,   60,   65,    0,   66,   65,
       59,   66,    0,   63,   64,   67,    0,   65,   67,   60,
       60,   61,   67,    0,   66,   69,   68,   77,   69,   68,
       77,   64,    0,   78,    0,   69,   78,   65,    0,   66,
       64,   79,   68,   65,   79,    0,   67,   68,   67,   80,
       66,  115,   80,    0,    0,   80,   69,   68,   77,    0,
       81,   69,   79,   81,   78,    0,    0,   82,   68,   77,
       82,    0,   79,   82,   68,   84,   83,    0,   84,   83,
       80,   80,   83,   81,    0,   84,    0,   85,    0,   79,

       85,   81,   86,   88,   85,   86,   88,   87,   82,   82,
       87,    0,   92,    0,    0,   92,   84,   83,   83,   88,
       81,   84,   86,    0,   87,    0,   89,    0,   85,   89,
       85,    0,   90,   86,   88,   90,   89,    0,   87,    0,
        0,   91,   90,   92,   91,   88,    0,    0,   86,   93,
       87,   91,   93,   98,    0,    0,   98,   89,    0,    0,
       91,   98,   89,   90,   94,    0,   93,   94,   90,    0,
        0,    0,   91,   95,   94,   96,   95,   91,   96,   97,
       93,    0,   97,   95,   98,  116,   91,   98,  116,    0,
       99,   96,   93,   99,  117,   94,    0,  117,  118,    0,

       94,  118,  119,   97,   95,  119,   96,    0,    0,   95,
       97,   99,  120,    0,    0,  120,  116,   96,    0,  118,
        0,   99,    0,  119,  122,  117,    0,  122,    0,  118,
       97,  116,    0,  119,  121,  120,    0,  121,   99,    0,
        0,  121,  123,  120,    0,  123,  118,  122,  124,  125,
      119,  124,  125,    0,  126,  122,  127,  126,  123,  127,
      128,    0,  120,  128,  126,  121,  129,  121,  130,  129,
        0,  130,  132,  123,  122,  132,    0,    0,  129,  124,
      125,  128,    0,  127,  123,  126,  131,  127,    0,  131,
      126,  128,  131,  132,    0,    0,    0,  129,  133,  130,

        0,  133,  134,  132,  129,  134,  133,    0,  128,    0,
      127,  135,  134,  136,  135,    0,  136,  131,  131,  140,
      132,  135,  140,    0,  137,  141,  136,  137,  141,  133,
        0,    0,  133,  134,  137,    0,  143,  142,  134,  143,
      142,    0,  135,    0,  136,  147,  143,  135,  147,    0,
      140,  142,  136,    0,  148,  137,  141,  148,  144,    0,
      137,  144,  147,  145,  144,    0,  145,  143,  142,    0,
        0,  146,  143,  145,  146,  149,  147,  142,  149,  151,
        0,  146,  151,  150,    0,  148,  150,    0,  147,  144,
      144,    0,  153,  150,  145,  153,    0,    0,  149,  145,

      151,  152,  146,    0,  152,  154,  149,  146,  154,  155,
      151,  152,  155,  157,  150,  153,  157,  162,  156,  150,
      162,  156,    0,  153,  156,  149,  161,  151,    0,  161,
        0,  155,  152,  161,    0,    0,  154,  152,  163,    0,
      155,  163,  153,  164,  157,    0,  164,    0,  162,  156,
      156,  165,  166,  167,  165,  166,  167,  161,  155,  161,
      163,    0,  166,  169,  168,  171,  169,  168,  171,  163,
      172,    0,  170,  172,  164,  170,  173,    0,  176,  173,
        0,  176,  165,  166,  167,  168,    0,  163,  166,  177,
      170,  169,  177,    0,  169,  168,  171,  173,    0,  177,

        0,  172,  176,  170,    0,  178,    0,  173,  178,  176,
      179,  180,  168,  179,  180,    0,  170,    0,  169,  181,
      177,    0,  181,  178,  173,  177,    0,  181,  182,  176,
      184,  182,  183,  184,  185,  183,  178,  185,    0,    0,
        0,  179,  180,  187,  186,  188,  187,  186,  188,  178,
      181,    0,    0,  181,  186,  183,    0,  185,    0,  182,
        0,  184,  187,  183,  189,  185,  190,  189,  191,  190,
      192,  191,    0,  192,  187,  186,  188,    0,  193,    0,
      186,  193,  183,    0,  185,    0,  189,  190,  187,    0,
        0,    0,  192,    0,    0,  189,    0,  190,    0,  191,

        0,  192,    0,    0,    0,    0,    0,    0,    0,  193,
        0,    0,    0,  189,  190,    0,    0,    0,    0,  192,
      196,  196,  196,  196,  197,  197,  197,  198,    0,  198,
      198,  199,    0,  199,  199,  200,    0,  200,  200,  201,
      201,  201,  202,    0,  202,  202,  203,    0,  203,  203,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "interface/lex.l"
#line 2 "interface/lex.l"
#include <stdio.h>
#ifndef FMACROS
   #include "../macros.h"
#endif
#ifndef FTYPES
   #include "../types.h"
#endif
#ifndef FPARSER
   #include "parser.h"
#endif
#include "y.tab.h"
#define YY_NO_INPUT
#line 751 "interface/lex.yy.c"
#line 752 "interface/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 18 "interface/lex.l"


#line 970 "interface/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 195 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 951 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "interface/lex.l"
return INSERT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "interface/lex.l"
return INTO;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "interface/lex.l"
return VALUES;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "interface/lex.l"
return SELECT;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "interface/lex.l"
return FROM;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "interface/lex.l"
return WHERE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "interface/lex.l"
return DELETE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "interface/lex.l"
return CREATE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "interface/lex.l"
return TABLE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "interface/lex.l"
return ON;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "interface/lex.l"
return INDEX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "interface/lex.l"
return INTEGER;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "interface/lex.l"
return LOGICO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "interface/lex.l"
return LOGICO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "interface/lex.l"
return INTEGER;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "interface/lex.l"
return VARCHAR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "interface/lex.l"
return CHAR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "interface/lex.l"
return DOUBLE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "interface/lex.l"
return PRIMARY;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "interface/lex.l"
return KEY;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "interface/lex.l"
return REFERENCES;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "interface/lex.l"
return DATABASE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "interface/lex.l"
return DROP;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "interface/lex.l"
return CONTR;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "interface/lex.l"
return IMPLEMENT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "interface/lex.l"
return HELP;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "interface/lex.l"
return HISTORY;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "interface/lex.l"
return HELP;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "interface/lex.l"
return HELP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "interface/lex.l"
return CLEAR;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "interface/lex.l"
return *yytext;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "interface/lex.l"
return *yytext;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "interface/lex.l"
return *yytext;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 "interface/lex.l"
return *yytext;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "interface/lex.l"
{yylval.strval = yytext; return FECHA_P;};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "interface/lex.l"
{yylval.strval = yytext; return ABRE_P;};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "interface/lex.l"
{yylval.strval = yytext; return ASTERISCO;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "interface/lex.l"
{ yylval.strval = yytext; return OBJECT; };
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 61 "interface/lex.l"
{yylval.strval = yytext; return STRING;};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "interface/lex.l"
{yylval.strval = yytext; return VALUE;};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "interface/lex.l"
{yylval.strval = yytext; return NUMBER;};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "interface/lex.l"
{yylval.strval = yytext; return OPERADOR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "interface/lex.l"
{yylval.strval = yytext; return RELACIONAL;};
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 68 "interface/lex.l"
{
									// if (GLOBAL_PARSER.mode != 0) {
									// 	if (GLOBAL_PARSER.parentesis)
									// 		printf("%s(# ", connected.db_name);
									// 	else
									// 		printf("%s-# ", connected.db_name);
									// } else if (connected.conn_active) {
								 	// 	if (GLOBAL_PARSER.consoleFlag)
							        //         GLOBAL_PARSER.consoleFlag = 0;
							        //     else
							        //         printf("%s=# ", connected.db_name);
									// } else
								 	// 	printf(">");
								};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "interface/lex.l"
return DELETE_HISTORY;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "interface/lex.l"
return CONNECT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 86 "interface/lex.l"
{invalidCommand("\\c <enter>'. Expecting '\\c DBNAME"); return 0;};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "interface/lex.l"
return LIST_DBASES;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "interface/lex.l"
return QUIT;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "interface/lex.l"
return LIST_TABLES;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "interface/lex.l"
return LIST_TABLE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "interface/lex.l"
{invalidCommand(yytext);};
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 95 "interface/lex.l"
{invalidCommand("\\t <enter>'. Expecting '\\t TABLENAME"); return 0;};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "interface/lex.l"
/* ignore whitespace */;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 98 "interface/lex.l"
ECHO;
	YY_BREAK
#line 1349 "interface/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 195 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 195 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 194);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 98 "interface/lex.l"


